name: 7501-env
channels:
- conda-forge
dependencies:
- python
- nb_conda_kernels
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- numdifftools
- zeus-mcmc
- corner
- mkl-service
- pydoe
