name: 7501-env
channels:
- conda-forge
- astropy
dependencies:
- python <3.11
- nb_conda_kernels
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- numdifftools
- emcee
- zeus-mcmc
- corner
- mkl-service
- pydoe
- ipympl
- sympy
